version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anyware-backend
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017/anyware
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: 'http://localhost:5050/api'
    container_name: anyware-frontend
    ports:
      - "7070:7070"
    depends_on:
      - backend
volumes:
  mongo-data:
